0306a

diff --git a/luci-app-ssr-plus/root/usr/bin/ssr-switch b/luci-app-ssr-plus/root/usr/bin/ssr-switch
--- a/luci-app-ssr-plus/root/usr/bin/ssr-switch
+++ b/luci-app-ssr-plus/root/usr/bin/ssr-switch
@@ -1,4 +1,4 @@
-#!/bin/sh /etc/rc.common
+#!/bin/sh  /etc/rc.common
 #
 # Copyright (C) 2017 openwrt-ssr
 # Copyright (C) 2017 yushi studio <ywb94@qq.com>
@@ -7,20 +7,28 @@
 # See /LICENSE for more information.
 #
 
-. $IPKG_INSTROOT/etc/init.d/shadowsocksr
-LOCK_FILE="/var/lock/ssr-switch.lock"
-[ -f "$LOCK_FILE" ] && exit 2
-touch "$LOCK_FILE"
-LOG_FILE=/var/log/ssrplus.log
-
 cycle_time=60
 switch_time=3
 normal_flag=0
 server_locate=0
 server_count=0
+NAME=shadowsocksr
 ENABLE_SERVER=nil
+CONFIG_SWTICH_FILE=/var/etc/${NAME}_t.json
+
 [ -n "$1" ] && cycle_time=$1
 [ -n "$2" ] && switch_time=$2
+
+uci_get_by_name() {
+	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
+	echo ${ret:=$3}
+}
+
+uci_get_by_type() {
+	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
+	echo ${ret:=$3}
+}
+
 DEFAULT_SERVER=$(uci_get_by_type global global_server)
 CURRENT_SERVER=$DEFAULT_SERVER
 
@@ -31,11 +39,11 @@ check_proxy() {
 	for i in $(seq 1 $try_count); do
 		/usr/bin/ssr-check www.google.com 80 $switch_time 1
 		if [ "$?" == "0" ]; then
-			# echolog "Check Google Proxy Success, count=$i"
+			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
 			result=0
 			break
 		else
-			# echolog "Check Google Proxy Fail, count=$i"
+			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
 			/usr/bin/ssr-check www.baidu.com 80 $switch_time 1
 			if [ "$?" == "0" ]; then
 				result=1
@@ -51,16 +59,17 @@ check_proxy() {
 test_proxy() {
 	local servername=$(uci_get_by_name $1 server)
 	local serverport=$(uci_get_by_name $1 server_port)
-	ipset add whitelist $servername 2>/dev/null
-	tcping -q -c 3 -i 1 -t 2 -p $serverport $servername
-	if [ "$?" -gt "0" ]; then
-		ipset del whitelist $servername 2>/dev/null
-		return 1
-	fi
+	ret=$(ping -c 3 $servername | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }')
+	[ -z "$ret" ] && return 1
+	[ "$ret" -gt "50" ] && return 1
+	ipset add ss_spec_wan_ac $servername 2>/dev/null
+	ret=$?
 	/usr/bin/ssr-check $servername $serverport $switch_time
-	local ret=$?
-	ipset del whitelist $servername 2>/dev/null
+	local ret2=$?
 	if [ "$ret" == "0" ]; then
+		ipset del ss_spec_wan_ac $servername 2>/dev/null
+	fi
+	if [ "$ret2" == "0" ]; then
 		return 0
 	else
 		return 1
@@ -70,24 +79,27 @@ test_proxy() {
 search_proxy() {
 	let server_count=server_count+1
 	[ "$normal_flag" == "1" -a "$server_count" -le "$server_locate" ] && return 0
-	[ "$(uci_get_by_name $1 switch_enable 0)" != "1" ] && return 1
+	[ "$(uci_get_by_name $1 switch_enable)" != "1" ] && return 1
 	[ $ENABLE_SERVER != nil ] && return 0
 	[ "$1" == "$CURRENT_SERVER" ] && return 0
 	local servername=$(uci_get_by_name $1 server)
 	local serverport=$(uci_get_by_name $1 server_port)
-	ipset add whitelist $servername 2>/dev/null
+	ipset add ss_spec_wan_ac $servername 2>/dev/null
+	ret=$?
 	/usr/bin/ssr-check $servername $serverport $switch_time
-	local ret=$?
-	ipset del whitelist $servername 2>/dev/null
+	local ret2=$?
 	if [ "$ret" == "0" ]; then
+		ipset del ss_spec_wan_ac $servername 2>/dev/null
+	fi
+	if [ "$ret2" == "0" ]; then
 		server_locate=$server_count
 		ENABLE_SERVER=$1
 		return 0
 	else
 		return 1
 	fi
-}
 
+}
 #选择可用的代理
 select_proxy() {
 	config_load $NAME
@@ -106,50 +118,51 @@ switch_proxy() {
 start() {
 	#不支持kcptun启用时的切换
 	[ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1" ] && return 1
+
 	while [ "1" == "1" ]; do #死循环
-		sleep 0000$cycle_time
+		sleep $cycle_time
 		LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
 		#判断当前代理是否为缺省服务器
 		if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ]; then
 			#echo "not default proxy"
-			echolog "Current server is not default Main server, try to switch back."
+			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >>/tmp/ssrplus.log
 			#检查缺省服务器是否正常
 			if test_proxy $DEFAULT_SERVER; then
 				#echo "switch to default proxy"
-				echolog "Main server is avilable."
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >>/tmp/ssrplus.log
 				#缺省服务器正常，切换回来
 				CURRENT_SERVER=$DEFAULT_SERVER
 				switch_proxy $CURRENT_SERVER
-				echolog "switch to default "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!"
+				echo "$(date "+%Y-%m-%d %H:%M:%S") switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!" >>/tmp/ssrplus.log
+				continue
 			else
-				echolog "Main server is NOT avilable.Continue using current server."
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >>/tmp/ssrplus.log
 			fi
 		fi
 		#判断当前代理是否正常
-		#echolog "Start checking if the current server is available."
 		check_proxy
 		current_ret=$?
 		if [ "$current_ret" == "1" ]; then
 			#当前代理错误，判断有无可用的服务器
 			#echo "current error"
-			echolog "Current server error, try to switch another server."
+			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >>/tmp/ssrplus.log
 			select_proxy
 			if [ "$ENABLE_SERVER" != nil ]; then
 				#有其他服务器可用，进行切换
 				#echo $(uci_get_by_name $new_proxy server)
-				echolog "Another server is avilable, now switching server."
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >>/tmp/ssrplus.log
 				CURRENT_SERVER=$ENABLE_SERVER
 				switch_proxy $CURRENT_SERVER
 				normal_flag=1
-				echolog "Switch to "$(uci_get_by_name $CURRENT_SERVER alias)" proxy!"
+				echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >>/tmp/ssrplus.log
 			else
 				switch_proxy $CURRENT_SERVER
 				normal_flag=1
-				echolog "Try restart current server."
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Try restart current server." >>/tmp/ssrplus.log
 			fi
 		else
 			normal_flag=0
-			# echolog "ShadowsocksR No Problem."
+			echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem." >>/tmp/ssrplus.log
 		fi
 	done
 }
